"""Human-reviewed interpretation of the bounded measurements; no metric optimism."""
import json
from build import *
PRIMARY=['upper_ascii','dec_x','copy_position','xor_copy','find_free','advance_history','store_history','dec_x_twice','tandy_copy','pit_delay']
REVIEW={
 'upper_ascii':('MATCH_DIFF_BORDERLINE',['CALLING_CONVENTION','ADDRESSING_MODE','STACK_FRAME','PROLOGUE_EPILOGUE','BLOCK_LAYOUT'],'Two early-return sites match after AL argument binding. Tiny recipe, but two sites choose half the eight output instructions; compiler-listing adapter is not a semantic frontend.'),
 'dec_x':('MATCH_DIFF_GOOD',['CALLING_CONVENTION','ADDRESSING_MODE','STACK_FRAME','PROLOGUE_EPILOGUE','BLOCK_LAYOUT'],'One guarded return layout; independent C-to-IR firewall. Actual ordinary-C ABI wrapper also verified. Five-instruction target makes even this a high constrained fraction.'),
 'copy_position':('MATCH_DIFF_GOOD',['CALLING_CONVENTION','ADDRESSING_MODE','STACK_FRAME','PROLOGUE_EPILOGUE'],'Body already has correct ordered load/add/store operations. Zero body constraints after two reviewed ABI pointer bindings; independent semantic firewall preserves alias order.'),
 'xor_copy':('VERIFIED_C_PREFERRED',['CALLING_CONVENTION','REGISTER_ALLOCATION','STACK_FRAME','SPILL_LOCATION','INSTRUCTION_SELECTION','BLOCK_LAYOUT','DEAD_FLAG_SHAPE'],'Original five-instruction XOR/MOVSB/LOOP loop is already compact. Explicit cursor results retained in C. Matching would have to select nearly every string/counter realization; no arbitrary-emission workaround attempted.'),
 'find_free':('VERIFIED_C_PREFERRED',['CALLING_CONVENTION','REGISTER_ALLOCATION','PROLOGUE_EPILOGUE','STACK_FRAME','BLOCK_LAYOUT','SPILL_LOCATION'],'All pool start/free pairs pass; original custom BX/CX outputs differ from C return/out parameter. Loop control and register allocation both differ. No small exact recipe demonstrated within bound.'),
 'advance_history':('MATCH_DIFF_BORDERLINE',['CALLING_CONVENTION','ADDRESSING_MODE','STACK_FRAME','PROLOGUE_EPILOGUE','BLOCK_LAYOUT'],'One return-edge constraint produces exact92-byte body after three global/pointer ABI bindings. Promising reuse, but14 operand bindings and compiler-text anchors are not yet a semantic firewall.'),
 'store_history':('VERIFIED_C_PREFERRED',['CALLING_CONVENTION','ADDRESSING_MODE','INSTRUCTION_SELECTION','INSTRUCTION_ORDER','PROLOGUE_EPILOGUE'],'C now returns next cursor and X explicitly. Original ES load and STOSW progression require boundary adaptation plus string-store lowering; no small exact recipe demonstrated.'),
 'dec_x_twice':('VERIFIED_C_PREFERRED',['CALLING_CONVENTION','BLOCK_LAYOUT','INSTRUCTION_SELECTION','STACK_FRAME'],'Use a closed routine-plus-tail unit. Two guarded decrements are readable C; original CALL-to-next-instruction plus fallthrough reuses one tail. No general stack-trick primitive admitted.'),
 'tandy_copy':('ASM_PREFERRED',['CALLING_CONVENTION','REGISTER_ALLOCATION','INSTRUCTION_SELECTION','INSTRUCTION_ORDER','STACK_FRAME','SPILL_LOCATION','BLOCK_LAYOUT'],'Full destination and cursor/width/remaining outputs pass. REP MOVSW, LOOP, bank-step carry handling and custom live registers dominate matching. Keep current DOS backend ASM; no claim C memory semantics are impossible.'),
 'pit_delay':('ASM_PREFERRED',['CALLING_CONVENTION','REGISTER_ALLOCATION','INSTRUCTION_SELECTION','STACK_FRAME','INSTRUCTION_ORDER','BLOCK_LAYOUT','OTHER'],'Corrected repeat-reload semantics pass five port scripts. Extra C calls/instructions alter physical timing, which protocol tests do not establish. Keep hardware timing loop ASM.')}

def summarize():
 code=read_json(HERE/'results/codegen.json');delta=read_json(HERE/'results/delta.json')['results'];sem=read_json(HERE/'results/semantics.json');c=(HERE/'clean/SAMPLE.C').read_text();rows=[]
 for f in code['sample']:
  if f['name'] not in PRIMARY:continue
  n=f['name'];body=re.search(r'(?:u8|u16|void) '+n+r'\([^)]*\)\s*\{(.*?)\n\}',c,re.S).group(1)
  loc=sum(bool(line.strip()) for line in body.splitlines());d=delta.get(n);target=f['builds']['tc_size'];outcome,taxonomy,reason=REVIEW[n]
  row=dict(name=n,address=f['address'],domain=f['domain'],clean_body_loc=loc,original_bytes=f['original_bytes'],original_instructions=target['original_instructions'],clean_tc_size_bytes=target['compiled_bytes'],clean_tc_size_instructions=target['compiled_instructions'],best_compiled_bytes=min(x['compiled_bytes'] for x in f['builds'].values()),natural_exact=any(x['exact'] for x in f['builds'].values()),behavioral_comparisons=sum(counts[n] for counts in sem['counts'].values()),outcome=outcome,mismatch_categories=taxonomy,interpretation=reason,deletion_test='PASS independent C compilation/execution; matching recipes not read',abi_shim='22 bytes +28 C bytes; full local ABI tested' if n=='upper_ascii' else '24 bytes +19 C bytes; full local ABI tested' if n=='dec_x' else 'Not implemented; do not infer zero cost')
  if d:
   row.update(match_constraints=d['match_constraints'],match_primitive_kinds=1 if d['match_constraints'] else 0,abi_bindings=d['abi_binding_constraints'],match_selected_instruction_fraction=2*d['branch_relayout_sites']/target['original_instructions'],abi_operand_selected_fraction=d['operand_rebound_instructions']/target['original_instructions'],recipe_bytes=len(json.dumps(d['recipe'],sort_keys=True).encode()),recipe_bytes_per_original_byte=len(json.dumps(d['recipe'],sort_keys=True).encode())/f['original_bytes'],machine_bytes_embedded_in_recipe=0,compiler_output_instructions_removed_for_abi=d['removed_instructions'],exact_with_abi_specialization_and_recipe=True)
  else:row.update(match_constraints=None,match_primitive_kinds=None,exact_with_abi_specialization_and_recipe=False,stop_reason='No exact recipe claimed. Mismatch estimates are qualitative, not invented delta measurements.')
  rows.append(row)
 write_json(HERE/'results/summary.json',dict(scope='10 primary routines selected after user narrowed the study;16 pilot routines retained transparently',rows=rows,pilot_routines=len(code['sample']),primary_routines=len(rows),all_comparisons=sum(sum(v.values()) for v in sem['counts'].values()),natural_exact=sum(r['natural_exact'] for r in rows),bounded_conclusion='Subset only. Two GOOD, two BORDERLINE demonstrations; not a general compiler/backend recommendation.',proposed_primitive_vocabulary=['conditional_return: joined|split'],reused_in_primary=['upper_ascii (two guards)','dec_x','advance_history'],firewall_source_forms=['two ordered copy-add stores','guarded field decrement'],not_proposed=['general register allocation','arbitrary instruction forms','loop/call-graph rewrite','dead flag override'],metrics_limit='Fractions count output instruction sites, not bits or independent semantic decisions. ABI and match constraints are deliberately separate. JSON text bytes are syntax-dependent.'))
 print('Research summary:',len(rows),'primary routines;',sum(r['natural_exact'] for r in rows),'natural exact')
if __name__=='__main__':summarize()
